### ISSUE TITLE
Simulator not showing updates

### ISSUE THREAD

**Issue by bcooke** [fingerproof/cordova-plugin-gapreload#3]
Hi Sebastien,

First off - thanks for the plugin! I use LiveReload when I code for the web and it's a huge time saver. I'm just starting out with PhoneGap and came across your plugin. Looks fantastic.

I've followed the steps exactly in the video, but I can't get my changes to appear in my simulator (I'm running a 4s simulator running iOS8). From what I can see, LiveReload is running the post-processing command and I think the simulator is refreshing.. it's just not reflecting the changes I make. The only major difference I notice is that my cordova server returns a bunch of 304s (with a 200 for the one file I edit) instead of a bunch of 200s like in your demo.

Have there been any changes to the cordova CLI that could be causing this? Sorry I can't provide much insight.. this is literally the first thing I'm trying with PhoneGap.

**Comment by sebastien-p** [comment]
Hi,

You're welcome, I'm glad you find GapReload useful!

I updated Cordova CLI, the iOS platform and iOS-sim on my Mac running `$ sudo npm install -g cordova ios-sim` and `$ cordova platform update ios` (that one in the app folder). So now _iOS project is now at version 3.6.3_ and `$ npm ls -g --depth 0` lists _cordova@4.0.0_ and _ios-sim@3.0.0_ which all are the latest stable versions. My Xcode version is _6.1 (6A1052d)_, latest Mac App Store version. Finally my Node.js and NPM versions are _0.10.25_ and _1.3.24_ (`$ node -v && npm -v`) which are not the most recent available, but I'm not sure this matters anyway.

Now when I run `$ cordova emulate ios && cordova serve`, wait for "_Static file server running on port 8000 (i.e. http://localhost:8000) CTRL + C to shut down_" to show up in my terminal window before accepting to use GapReload in my iPhone 4s iOS 8 simulator window, everything works as expected. I mean I only get 304s when saving CSS files, every other files I request give me 200s. LiveReload handles CSS files a bit differently, injecting style rules instead or reloading the whole page so I guess this is normal.

The GapReload video demo is a bit outdated, some configurations variables have since been renamed (_*_HOST_ instead of _*_HOSTNAME_), you also need to setup LiveReload to exclude the _hooks_ directory. And **most important of all**, have to configure LiveReload to run _cordova prepare_ as a custom command after processing changes (apparently you did that - then double check for typos). Also, please, make sure to install GapReload using its Cordova repository plugin id instead of this Git repo URL.

By the way, my Mac is running Yosemite _10.10 (14A389)_, I was using LiveReload _2.3.34_ and [updated to 2.3.66](http://feedback.livereload.com/knowledgebase/articles/67441-how-do-i-start-using-livereload) (the Mac App Store version is quite old). Note that even the latest LiveReload app version seems to be a bit unstable on Yosemite.

One more thing, you can try using [Safari remote debugging tools](http://moduscreate.com/enable-remote-web-inspector-in-ios-6/) (pretty much the same procedure to enable the feature on iOS 8) to inspect your app in the simulator and check for JavaScript errors that could prevent LiveReload to work correctly.

Hopefully this will help you use GapReload. Thank you for reporting issues, this is how we can improve the plugin and help people building great Cordova apps easily. :smiley:

**Comment by bcooke** [comment]
Thanks for the speedy response!

I double-checked my configuration. Everything is set up as described, but I still can't get gapreload to work. I've made a little bit of progress diagnosing the problem. Even though I have 'cordova prepare' set as the post-processing command, it's not actually executing.. as I can see my changes aren't being mirrored from /www/index.html to /platforms/ios/www/index.html.

If I invoke the command myself, and then make a change to /www/index.html (since that's the watched directory), the simulator loads the changes in a few seconds.

I'll spend some more time trying to figure out what's blocking the command and share my findings.

**Comment by bcooke** [comment]
And just like that, problem solved.

Apparently LiveReload lies when it says that: "This command will be invoked in the project directory after running compilers but before refreshing browsers."

It actually executes the command in the system root directory.. so needless to say, that's why cordova prepare wasn't working as expected.

You can fix this by telling LiveReload to cd into the cordova project, so it's:

cd ~/Documents/myapp && cordova prepare

rather than simply:

cordova prepare

Thanks again for the help and the plugin Sebastien.. not really sure why this affects me and not you, but I hope this might help somebody utilize your great plugin in the future. Cheers!

**Comment by sebastien-p** [comment]
Thank you for letting me know. I guess you're on Yosemite, what LiveReload app version du you use? The issue is pretty weird, never faced it myself.

**Comment by sebastien-p** [comment]
I think I know why you faced this issue and I'm not. I always add the Cordova app root folder to LiveReload, maybe you added a parent one. That would explain why `cordova prepare` fails in your case and you have to explicitly `cd` into the root app directory to make it work. I'll document that.
